robotState = {
        'driving': False,
        'current_speed': 0,
        'current_steering_angle': 0,
        'road_clear': True,
        'closing_down': True,
        'watching_road_markings': False,
        'was_used_watch_road_markings': False,
        'read_distance_timeout': 0.02,
        'distance': 0,
        'watching_distance': False,
        'was_used_watch_distance': False,
        'line_found': False,
        'is_on_line': False,
        'is_following_line': False,
        'read_road_markings_timeout': 0.02,
        'changed_road_markings': False,
        'grayscale_sensitivity': 400,
        'grayscale_threshold_margin': 0.3,
        'road_markings': [
                [False, False, False],
             ],
        'driving_speeds': {
            'stopped': 0,
            'forwards': 30,
            'reverse': 10,
            'forwards_line_follow': 25,
            'reverse_line_follow': 5,
            'cornering': 15,
            },
        'steering_angles': {
            'sharp_right': 45,
            'shallow_right': 15,
            'sharp_left': -45,
            'shallow_left': -15,
            },
        'last_visited_intersection': None,
        'bearing': 'north',
        }
