robotState = {
        'driving': False,
        'current_speed': 0,
        'current_steering_angle': 0,
        'road_clear': True,
        'closing_down': True,
        'watching_road_markings': False,
        'was_used_watch_road_markings': False,
        'distance': 0,
        'watching_distance': False,
        'was_used_watch_distance': False,
        'line_found': False,
        'is_on_line': False,
        'is_following_line': False,
        'changed_road_markings': False,
        'grayscale_sensitivity': 400,
        'road_markings': {
            'left_sensor': False,
            'middle_sensor': False,
            'right_sensor': False,
            },
        'driving_speeds': {
            'forwards_line_follow': 50,
            'reverse_line_follow': 30,
            'cornering': 25,
            },
        'steering_angles': {
            'sharp_right': 45,
            'shallow_right': 15,
            'sharp_left': -45,
            'shallow_left': -15,
            },
        'last_visited_intersection': None,
        'bearing': 'north',
        }
